# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-02-07 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar_promotions', '0002_auto_20150604_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBasedPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('available_since_date', models.DateField(blank=True, null=True)),
                ('available_since_time', models.TimeField()),
                ('available_until_date', models.DateField(blank=True, null=True)),
                ('available_until_time', models.TimeField()),
                ('promotional_code', models.CharField(max_length=50, blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
