# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-06-27 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar_promotions', '0004_timebasedpromotion_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='timebasedpromotion',
            name='call_to_action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
