# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-07-06 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar_promotions', '0005_timebasedpromotion_call_to_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebasedpromotion',
            name='promotional_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
