# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-14 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oscar_promotions', '0006_auto_20180706_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageExtraInfo',
            fields=[
                ('description', models.TextField(verbose_name='Description for mobile view')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_info', serialize=False, to='oscar_promotions.Image')),
            ],
            options={
                'verbose_name': 'ImageExtraInfo',
                'verbose_name_plural': 'ImageExtraInfo',
            },
        ),
    ]
