# Generated by Django 2.2.12 on 2020-07-02 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('oscar_promotions', '0008_auto_20190802_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='timebasedpromotion',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
