language: python
sudo: false

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36-django22
    - python: 3.7
      env: TOXENV=py37-django22

    - python: 3.6
      env: TOXENV=lint

branches:
  only:
    - master

install:
    - pip install tox codecov

script:
    - tox

after_success:
  - tox -e coverage-report
  - codecov
